### ISSUE TITLE
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'chapignon.hoenn.pkmn' ([Errno -2] Name or service not known)")

### ISSUE THREAD

**Issue by SThomaty** [s-leroux/PyramidDemo#1]
Hi!
Thanks for this great tutorial project. 
Unfortunately I've some troubles  running the `initialize_PyramidDemo_db development.ini ` command after modifying the `sqlalchemy.url` field 

Is the database always running and valid?

Here is the error message :

> Traceback (most recent call last):
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 1122, in _do_get
>     return self._pool.get(wait, self._timeout)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/util/queue.py", line 145, in get
>     raise Empty
> sqlalchemy.util.queue.Empty
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/PyMySQL-0.7.9-py3.5.egg/pymysql/connections.py", line 890, in connect
>     (self.host, self.port), self.connect_timeout)
>   File "/usr/lib/python3.5/socket.py", line 693, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
>   File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno -2] Name or service not known
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
>     return fn()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 387, in connect
>     return _ConnectionFairy._checkout(self)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 766, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 516, in checkout
>     rec = pool._do_get()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 1138, in _do_get
>     self._dec_overflow()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 187, in reraise
>     raise value
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 1135, in _do_get
>     return self._create_connection()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 333, in _create_connection
>     return _ConnectionRecord(self)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 461, in __init__
>     self.__connect(first_connect_check=True)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 651, in __connect
>     connection = pool._invoke_creator(self)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 105, in connect
>     return dialect.connect(*cargs, **cparams)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 393, in connect
>     return self.dbapi.connect(*cargs, **cparams)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/PyMySQL-0.7.9-py3.5.egg/pymysql/__init__.py", line 90, in Connect
>     return Connection(*args, **kwargs)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/PyMySQL-0.7.9-py3.5.egg/pymysql/connections.py", line 688, in __init__
>     self.connect()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/PyMySQL-0.7.9-py3.5.egg/pymysql/connections.py", line 937, in connect
>     raise exc
> pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'chapignon.hoenn.pkmn' ([Errno -2] Name or service not known)")
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/bin/initialize_PyramidDemo_db", line 9, in <module>
>     load_entry_point('PyramidDemo==0.0', 'console_scripts', 'initialize_PyramidDemo_db')()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/PyramidDemo-0.0-py3.5.egg/pyramiddemo/scripts/initializedb.py", line 37, in main
>     Base.metadata.create_all(engine)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/sql/schema.py", line 3860, in create_all
>     tables=tables)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1919, in _run_visitor
>     with self._optional_conn_ctx_manager(connection) as conn:
>   File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
>     return next(self.gen)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1912, in _optional_conn_ctx_manager
>     with self.contextual_connect() as conn:
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2103, in contextual_connect
>     self._wrap_pool_connect(self.pool.connect, None),
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2142, in _wrap_pool_connect
>     e, dialect, self)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
>     exc_info
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 203, in raise_from_cause
>     reraise(type(exception), exception, tb=exc_tb, cause=cause)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 186, in reraise
>     raise value.with_traceback(tb)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
>     return fn()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 387, in connect
>     return _ConnectionFairy._checkout(self)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 766, in _checkout
>     fairy = _ConnectionRecord.checkout(pool)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 516, in checkout
>     rec = pool._do_get()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 1138, in _do_get
>     self._dec_overflow()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
>     compat.reraise(exc_type, exc_value, exc_tb)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 187, in reraise
>     raise value
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 1135, in _do_get
>     return self._create_connection()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 333, in _create_connection
>     return _ConnectionRecord(self)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 461, in __init__
>     self.__connect(first_connect_check=True)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/pool.py", line 651, in __connect
>     connection = pool._invoke_creator(self)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/strategies.py", line 105, in connect
>     return dialect.connect(*cargs, **cparams)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/SQLAlchemy-1.1.5-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 393, in connect
>     return self.dbapi.connect(*cargs, **cparams)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/PyMySQL-0.7.9-py3.5.egg/pymysql/__init__.py", line 90, in Connect
>     return Connection(*args, **kwargs)
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/PyMySQL-0.7.9-py3.5.egg/pymysql/connections.py", line 688, in __init__
>     self.connect()
>   File "/home/User/Documents/PyramidProj/Projects/pyramid-demo/lib/python3.5/site-packages/PyMySQL-0.7.9-py3.5.egg/pymysql/connections.py", line 937, in connect
>     raise exc
> sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'chapignon.hoenn.pkmn' ([Errno -2] Name or service not known)")

**Comment by SThomaty** [comment]
All my fault, I forgot to modify the @hapignon.hoenn.pkmn part of the command ! Sorry for the inconvenience.
